Rewrite and update !tag bridge.
ravener/termux-bot pull request #14
Opened 2023-12-03 02:13 UTC by tstein

2023-12-03 02:40 UTC, tstein commented on data/tags.json
> -      "To not force people to use one specific chat platform, we connected <#641256914684084237> and <#847704138711171084> channels to relay messages into Matrix: <https://matrix.to/#/#Termux:matrix.
About the matrix space: I think this does need a list of channels. Not sure how useful linking the space is, and we'd need to update it for #coding. Thoughts welcome.

2023-12-06 09:55 UTC, ravener requested changes

2023-12-06 09:55 UTC, ravener commented on data/tags.json
> +      "Not everyone likes Discord! We bridge several Discord channels with Matrix rooms so more people can join. Users on both sides see all users and messages from both. If you are using Discord, a
```suggestion
      "Not everyone likes Discord! We bridge several Discord channels with Matrix rooms so more people can join. Users on both sides see all users and messages from both. If you are using Discord, a webhook causes Matrix users to appear as bots.",
```

2023-12-06 16:51 UTC, tstein commented on data/tags.json
> +      "Not everyone likes Discord! We bridge several Discord channels with Matrix rooms so more people can join. Users on both sides see all users and messages from both. If you are using Discord, a
Whoops. Thanks for catching that.

2023-12-06 20:23 UTC, merged